### ISSUE TITLE
Inter-line height is not the same as it used to be. (2.002 vs 1.013)

### ISSUE THREAD

**Issue by fearthecowboy** [googlefonts/Inconsolata#9] opened 2017-04-25 22:16 UTC
(apologies for not knowing the 'font-terminology'... )

I recently downloaded a new version of Inconsolata and it has some significant changes from the previous:

![image](https://cloud.githubusercontent.com/assets/133736/25410119/d6405dfa-29c9-11e7-9184-59d66185df08.png)

There is a ton of extra whitespace in there... it doesn't feel right anymore 😢 

Is that what you intended?

**Comment by davelab6** [comment] 2017-04-25 22:22
Where (what programs/OS) are you seeing that?

**Comment by fearthecowboy** [comment] 2017-04-25 22:24
Windows 10 (the built-in font viewer),

after installing the new version of the font, my console windows seemed way out of whack, so I did some investigating.

**Comment by fearthecowboy** [comment] 2017-04-25 22:38
Hmm. I think VSCode (which is electron-based) isn't doing the same thing... 

Weird: the console window (which I made translucent) is rendering different than the vscode editor (behind, and fainter)

You can see they start off around the same, but they eventually end up different: 

![image](https://cloud.githubusercontent.com/assets/133736/25410670/0f7ffa82-29cd-11e7-9e3c-1204c05af75d.png)

**Comment by fearthecowboy** [comment] 2017-04-25 22:39
It feels like the console window is squishing the font when it renders

**Comment by fearthecowboy** [comment] 2017-04-25 22:42
Hey @bitcrazed is it possible that the font renderer for the console window is doing something weird here? 

I'd think I shouldn't see differences in the same font between VSCode and the console.

**Comment by fearthecowboy** [comment] 2017-04-25 22:47
Both the Font Viewer and the console use GDI, which we may have run into a funny bug in the latest font.

**Comment by alexeiva** [comment] 2017-04-27 07:18
_Left: Inco 1 | Right: Inco 2_
<img width="679" alt="screen shot 2017-04-27 at 10 15 11 am" src="https://cloud.githubusercontent.com/assets/16634089/25472087/7a5e6670-2b32-11e7-82bd-9bc7cde05fef.png">

Regression test shows identical v-metrics
<img width="982" alt="screen shot 2017-04-27 at 10 12 54 am" src="https://cloud.githubusercontent.com/assets/16634089/25472095/7e9589d0-2b32-11e7-97c2-6008abcdd5d0.png">

**Comment by alexeiva** [comment] 2017-04-27 07:24
My guess is the renderer uses winAscent(1004) to calculate line-heights instead of typoAscender(859). winAscent is meant for preventing clipping in tall glyphs, while typoAscender should affect line-height.

**Comment by bitcrazed** [comment] 2017-04-27 14:17
It's likely that GDI is calculating max height for a tall char because fixed width fonts are usually used in grid layouts (e.g. Console/terminal apps). Will check

**Comment by fearthecowboy** [comment] 2017-07-11 15:04
@bitcrazed any progress on this?

**Comment by davelab6** [comment] 2018-03-23 02:38
I'm going to close this as I assume the metrics are staying as they are now. Please re-open or file a new issue if this is still a problem for you :)

**Closed by davelab6** 2018-03-23 02:38 UTC
